### ISSUE TITLE
No attribute 'blas_opt_info'

### ISSUE THREAD

**Issue by goerz** [BoxiLi/qutip-qip-paper#5]
I'm currently unable to run the example due to https://github.com/qutip/qutip/issues/1753

This looks like it's a problem with QuTiP, but I'm just opening this issue to keep track of it

**Comment by BoxiLi** [comment]
Seems a problem with the newest NumPy changing the key of blas in `__config__`. There is already a solution proposed https://github.com/qutip/qutip/pull/1752.

For now it works for me to pin `python==3.9` and `numpy==1.21`.

**Comment by goerz** [comment]
Can confirm, `numpy==1.21` works (also with Python 3.8)
